[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "bu-backend"

[services.variables]
NODE_ENV = "production"
PORT = "3005"

[[services.ports]]
port = 3005
handle = "http"

[services.port.env]
PORT = "{{ .port }}"