[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30000
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm start"

[[services]]
name = "bu-backend"

[services.variables]
NODE_ENV = "production"
PORT = "3005"

[[services.ports]]
port = 3005
handle = "http"

[services.port.env]
PORT = "{{ .port }}"